### ISSUE TITLE
坑呀

### ISSUE THREAD

**Issue by hsowan** [echisan/springboot-jwt-demo#10]
文章里的:
![image](https://user-images.githubusercontent.com/26451706/60702080-6861d780-9f30-11e9-8dbf-96ae9dd40252.png)

代码里的:
![image](https://user-images.githubusercontent.com/26451706/60702106-7ca5d480-9f30-11e9-8819-c86dea407258.png)

**Comment by galaxist** [comment]
怎么了？

**Comment by hsowan** [comment]
> 怎么了？

文章中的条件和代码中的是不一样的

**Comment by galaxist** [comment]
看到了 有个！的区别，我当时架构选型时关注了这个的，但测试这个代码有问题，现在转到jeecg-boot了。其实我还蛮喜欢ss的权限框架的。。。

**Comment by hsowan** [comment]
> jeecg-boot

这个jb好像很厉害的样子

**Comment by echisan** [comment]
不好意思了，忘记改了。。之前也有人提过这个。。

**Comment by hsowan** [comment]
@echisan 
![image](https://user-images.githubusercontent.com/26451706/60708457-b54daa00-9f40-11e9-9ac9-361bb6db204d.png)

突然冒出这个方法

**Comment by echisan** [comment]
> @echisan
> ![image](https://user-images.githubusercontent.com/26451706/60708457-b54daa00-9f40-11e9-9ac9-361bb6db204d.png)
> 
> 突然冒出这个方法

内容不多就没特意写出来了。。

**Comment by hsowan** [comment]
### **没点耐心还真不行**
代码里的:
![image](https://user-images.githubusercontent.com/26451706/60718051-3b282000-9f56-11e9-81f9-05e6ab2bbe59.png)

文章里的:
![image](https://user-images.githubusercontent.com/26451706/60718085-52ffa400-9f56-11e9-867c-dc57ea09ae6d.png)

**Comment by echisan** [comment]
hasRole跟hasAuthority是不一样的。。

**Comment by hsowan** [comment]
> hasRole跟hasAuthority是不一样的。。

我也发现了，所以一直报403

**Comment by echisan** [comment]
直接跑我的demo应该是没有问题的，但是如果你边看博客边看代码可能就有点出入了，因为博客是循序渐进地写的，代码是最终版，所以博客里面一些片段是一个中间态的存在

**Comment by hsowan** [comment]
还是非常感谢！
