### ISSUE TITLE
security配置问题

### ISSUE THREAD

**Issue by ZongZihao** [echisan/springboot-jwt-demo#11]
`.antMatchers(HttpMethod.DELETE, "/tasks/**").hasRole("ADMIN")`

这个配置好像没有起作用, 运行你的demo, 只有在控制器方法上加注解之后角色权限校验才会有效, 不明白为什么.

**Comment by echisan** [comment]
可能要用antMatchers(HttpMethod.DELETE, "/tasks/**"). **hasAuthority("ROLE_ADMIN")** 才能生效把（大概

**Comment by LearnerForeverjack** [comment]
希望伟大的作者能进一步完善，已给star

**Comment by zhuxl13817468272** [comment]
伟大的作者  antMatchers(HttpMethod.DELETE, "/tasks/**"). hasAuthority("ROLE_ADMIN") 这句话也不能生效，只能在delete方法上加注解才能生效。
我想问一个问题：JWTAuthenticationFilter的attemptAuthentication方法中
return authenticationManager.authenticate( 
                    new UsernamePasswordAuthenticationToken(loginUser.getUsername(), loginUser.getPassword(), new ArrayList<>())
            );
这句代码不知道在哪里发出sql: select id ,password ,role ,username from jd_user where username =?
请大佬解释一波~~~非常感谢伟大作者的贡献此项目~~

**Comment by zhuxl13817468272** [comment]
伟大的作者 antMatchers(HttpMethod.DELETE, "/tasks/**"). hasAuthority("ROLE_ADMIN") 这句话也不能生效，只能在delete方法上加注解才能生效。
********************************************************************************************************
我想问一个问题：JWTAuthenticationFilter的attemptAuthentication方法中
return authenticationManager.authenticate(
          new UsernamePasswordAuthenticationToken(loginUser.getUsername(), loginUser.getPassword(), new ArrayList<>()));
这句代码不知道在哪里发出sql: select id ,password ,role ,username from jd_user where username =?
请大佬解释一波

~~~非常感谢伟大作者的贡献此项目~~

**Comment by zhuxl13817468272** [comment]
伟大的作者 antMatchers(HttpMethod.DELETE, "/tasks/**"). hasAuthority("ROLE_ADMIN") 这句话也不能生效，只能在delete方法上加注解才能生效。
我想问一个问题：JWTAuthenticationFilter的attemptAuthentication方法中
return authenticationManager.authenticate(
new UsernamePasswordAuthenticationToken(loginUser.getUsername(), loginUser.getPassword(), new ArrayList<>())
);
这句代码不知道在哪里发出sql: select id ,password ,role ,username from jd_user where username =?
请大佬解释一波。非常感谢伟大作者的贡献此项目！！！

**Comment by zhuxl13817468272** [comment]
伟大的作者 antMatchers(HttpMethod.DELETE, "/tasks/**"). hasAuthority("ROLE_ADMIN") 这句话也不能生效，只能在delete方法上加注解才能生效。
********************************************************************************************************
我想问一个问题：JWTAuthenticationFilter的attemptAuthentication方法中
return authenticationManager.authenticate(
new UsernamePasswordAuthenticationToken(loginUser.getUsername(), loginUser.getPassword(), new ArrayList<>()));
这句代码不知道在哪里发出sql: select id ,password ,role ,username from jd_user where username =?
请大佬解释一波……
----万分感谢大佬贡献此项目！！！----

**Comment by zhuxl13817468272** [comment]
.antMatchers(HttpMethod.DELETE, "/tasks/**").hasRole("ADMIN")
或者antMatchers(HttpMethod.DELETE, "/tasks/**"). hasAuthority("ROLE_ADMIN")   要放在匹配规则的最前面就生效了，结果："统一处理，原因：Access is denied"

**Comment by zhuxl13817468272** [comment]
另外，我想问一个问题：JWTAuthenticationFilter的attemptAuthentication方法中
return authenticationManager.authenticate(
new UsernamePasswordAuthenticationToken(loginUser.getUsername(), loginUser.getPassword(), new ArrayList<>()));
这句代码不知道在哪里发出sql: select id ,password ,role ,username from jd_user where username =?
请大佬解释一波……

**Comment by echisan** [comment]
@ZongZihao @LearnerForeverjack @zhuxl13817468272 

刚刚看了下SecurityConfig
```java
// 原来的顺序是这样的
.antMatchers("/tasks/**").authenticated()
.antMatchers(HttpMethod.DELETE, "/tasks/**").hasRole("ADMIN")
```
看了看源码，这一步其实就是将规则放到`List<RequestMatcher>`中放到末尾，所以匹配的顺序应该是
1. `/tasks/**` 认证用户可以请求所有方法
2. `/tasks/**` 认证用户且角色为`ADMIN`才请求`DELETE`方法

所以根据匹配顺序，所有用户在第一步已经匹配成功，就已经返回不继续往下执行了，所以`.antMatchers(HttpMethod.DELETE, "/tasks/**").hasRole("ADMIN")`这个规则没有生效。

那么现在只需要把顺序换一下
```java
.antMatchers(HttpMethod.DELETE, "/tasks/**").hasRole("ADMIN")
.antMatchers("/tasks/**").authenticated()
```
此时再次以`USER`角色请求该路径
```
DELETE http://localhost:8102/tasks/1

HTTP/1.1 403 
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: application/json;charset=utf-8
Content-Length: 42
Date: Fri, 01 Nov 2019 03:37:16 GMT

"统一处理，原因：Access is denied"

Response code: 403; Time: 73ms; Content length: 26 bytes
```

此时再修改数据库，将role修改成`ROLE_ADMIN`，再次请求
```
DELETE http://localhost:8102/tasks/1

HTTP/1.1 200 
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: text/plain;charset=UTF-8
Content-Length: 25
Date: Fri, 01 Nov 2019 03:38:48 GMT

删除了id为:1的任务

Response code: 200; Time: 127ms; Content length: 11 bytes
```

所以主要是顺序反了导致的不生效。

**Comment by echisan** [comment]
> 另外，我想问一个问题：JWTAuthenticationFilter的attemptAuthentication方法中
> return authenticationManager.authenticate(
> new UsernamePasswordAuthenticationToken(loginUser.getUsername(), loginUser.getPassword(), new ArrayList<>()));
> 这句代码不知道在哪里发出sql: select id ,password ,role ,username from jd_user where username =?
> 请大佬解释一波……

这里看一下源码就大概知道了
```java
authenticationManager.authenticate(
                    new UsernamePasswordAuthenticationToken(loginUser.getUsername(), loginUser.getPassword(), new ArrayList<>())
```
这里请求了`authenticate()`方法，最后会请求到这个类`AbstractUserDetailsAuthenticationProvider`的`authenticate()`方法  

然后会执行下面的方法
```java
user = retrieveUser(username,(UsernamePasswordAuthenticationToken) authentication);
```

`retrieveUser`方法
```java
protected final UserDetails retrieveUser(String username,
			UsernamePasswordAuthenticationToken authentication)
			throws AuthenticationException {
		prepareTimingAttackProtection();
		try {
// 这里就执行了我们之前写的UserDetailService里的loadUserByUsername方法去插数据库了
			UserDetails loadedUser = this.getUserDetailsService().loadUserByUsername(username);
			if (loadedUser == null) {
				throw new InternalAuthenticationServiceException(
						"UserDetailsService returned null, which is an interface contract violation");
			}
			return loadedUser;
		}catch(){
                    // ....
              }
	}
```

**Comment by zhuxl13817468272** [comment]
大佬，完美解答~~很牛逼~~~佩服佩服~~
