### ISSUE TITLE
auth/login此接口确定可以直接访问吗？

### ISSUE THREAD

**Issue by ZPLOVEXYH** [echisan/springboot-jwt-demo#14]
为何我down下来你的代码，启动之后可以访问注册接口，但是登陆接口没法访问呀。

**Comment by echisan** [comment]
注意参数，rememberMe是必须的
[参数详情](https://github.com/echisan/springboot-jwt-demo#%E4%BD%BF%E7%94%A8)

**Comment by ZPLOVEXYH** [comment]
嗯，可以获取到了，谢谢大神。
