### ISSUE TITLE
Redis问题

### ISSUE THREAD

**Issue by Erisu0014** [echisan/springboot-jwt-demo#16]
您好，请问您现在实现redis管理token了吗。请问您用的是jedis还是redisTemplate呢。我现在的项目是用的第二种，但是redisTemplate是基于注解式的，感觉不能在filter里做逻辑处理，请问您是怎么解决的呢

**Comment by echisan** [comment]
Filter可以声明为bean的把
```java
@Bean
public Filter filter(){
  return new Filter();
}
```

如果你是用springsecurity的话，在security的config类里尝试一下这样的配置
https://github.com/DMCollection/danmakuji-api/blob/master/src/main/java/cc/dmji/api/security/SecurityConfig.java#L94

**Comment by Erisu0014** [comment]
我尝试了一下，然后将JWTauthenticationFilter上加了@component注解，通过@autowired导入了authenticationManager，然后就启动不了了。因为authenticationManager必须是specified的，怎么解决呢

**Comment by echisan** [comment]
在你的SecurityConfig里面加上下面的，`JWTauthenticationFilter`不用`@component`注解，在你的config文件下用`@Bean` 然后把`AuthenticationManager`弄进去
```java
    @Bean(name = BeanIds.AUTHENTICATION_MANAGER)
    @Override
    public AuthenticationManager authenticationManagerBean() throws Exception {
        return super.authenticationManagerBean();
    }


    @Bean
    public JWTAuthorizationFilter jwtAuthorizationFilter() throws Exception {
        return new JWTAuthorizationFilter(authenticationManagerBean());
    }
```
```

**Comment by Erisu0014** [comment]
哦哦我试一试，谢谢大佬，帮大忙了
