### ISSUE TITLE
readme里加个建表语句吧

### ISSUE THREAD

**Issue by shluoyujun** [echisan/springboot-jwt-demo#23]
`CREATE TABLE IF NOT EXISTS `jd_user`(
   `id` INT UNSIGNED AUTO_INCREMENT,
   `username` VARCHAR(512) NOT NULL,
   `password` VARCHAR(512) NOT NULL,
   `role` VARCHAR(512) NOT NULL,
   PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;`

**Comment by echisan** [comment]
jpa会自动键表的

**Comment by shluoyujun** [comment]
的确是，赞👍
