### ISSUE TITLE
怎么获取已登录用户的信息？？

### ISSUE THREAD

**Issue by cjcj125125** [echisan/springboot-jwt-demo#3]
如题，shiro 用SecurityUtils.getSubject().getPrincipal(); 
security用哪个方法获取？？谢谢

**Comment by Jonny023** [comment]
```
// 获取用户名
String loginName = (String) SecurityUtils.getSubject().getPrincipal();

// 然后根据用户名查询
User user = userService.findByUsername(loginName); 
```
或者强转试试(不过这种方式没试过)
```
User user= (User)SecurityUtils.getSubject().getPrincipal();
```

**Comment by xx13295** [comment]
> 如题，shiro 用SecurityUtils.getSubject().getPrincipal();
> security用哪个方法获取？？谢谢

Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
if (!(authentication instanceof AnonymousAuthenticationToken)) {
    String currentUserName = authentication.getName();
    return currentUserName;
}

**Comment by echisan** [comment]
[https://github.com/echisan/springboot-jwt-demo/blob/master/src/main/java/cn/echisan/springbootjwtdemo/filter/JWTAuthenticationFilter.java#L60](https://github.com/echisan/springboot-jwt-demo/blob/master/src/main/java/cn/echisan/springbootjwtdemo/filter/JWTAuthenticationFilter.java#L60)emmm指的是这个吗

**Comment by cjcj125125** [comment]
另外问一下，怎么修改密码加密解密规则？以前用的shiro 密码是Sha256Hash  密码+盐 的形式，现在要怎么改才能使用以前的？

**Comment by echisan** [comment]
@cjcj125125 这个不真不会= =
