### ISSUE TITLE
 登录的filter里面获取不到用户名和密码，求教

### ISSUE THREAD

**Issue by cjcj125125** [echisan/springboot-jwt-demo#4]
https://github.com/echisan/springboot-jwt-demo/blob/bb0d974361544084cffad9bb618b7c8d8b93264c/src/main/java/cn/echisan/springbootjwtdemo/filter/JWTAuthenticationFilter.java#L41

这里获取不到用户名和密码，不知道为啥

**Comment by cjcj125125** [comment]
![qq 20181018202104](https://user-images.githubusercontent.com/20206579/47154362-b6886980-d314-11e8-91f2-61dcb1167fb1.png)
你可以断点看看

**Comment by echisan** [comment]
@cjcj125125 你试试直接看看request里有没有内容
