### ISSUE TITLE
请问如何实现user,role，rest这种权限？

### ISSUE THREAD

**Issue by galaxist** [echisan/springboot-jwt-demo#5]
目前这个是只有user表，如果需要设计成用户角色关联，角色关联rest资源的话，该项目需要如何改造？

**Comment by echisan** [comment]
@galaxist 
我这个demo应该是已经有跟user跟role关联了的，可以看下下面的链接
[注册时候的](https://github.com/echisan/springboot-jwt-demo/blob/master/src/main/java/cn/echisan/springbootjwtdemo/controller/AuthController.java#L32)
[验证权限的时候](https://github.com/echisan/springboot-jwt-demo/blob/master/src/main/java/cn/echisan/springbootjwtdemo/filter/JWTAuthorizationFilter.java#L49)
[rest资源跟角色关联的时候，修改对应的hasRole就行了](https://github.com/echisan/springboot-jwt-demo/blob/master/src/main/java/cn/echisan/springbootjwtdemo/config/SecurityConfig.java#L49)

**Comment by galaxist** [comment]
这个是单一角色的吧？

**Comment by echisan** [comment]
你的role字段可以可以有多种角色的鸭，比如ROLE_USER，ROLE_ADMIN，ROLE_VISITOR等等，然后再去securityConfig里面配置不同的路径不同的权限

**Comment by galaxist** [comment]
我是用户 权限 角色都写入到数据库了呀，不在代码里配置了。

**Comment by echisan** [comment]
这个我母鸡了qaq

**Comment by galaxist** [comment]
https://github.com/echisan/springboot-jwt-demo/blob/bb0d974361544084cffad9bb618b7c8d8b93264c/src/main/java/cn/echisan/springbootjwtdemo/filter/JWTAuthenticationFilter.java#L62

请问这一段就是给角色了吧， 是不是只能给一个角色？

        boolean isRemember = rememberMe.get() == 1;

        String role = "";
        Collection<? extends GrantedAuthority> authorities = jwtUser.getAuthorities();
        for (GrantedAuthority authority : authorities){
            role = authority.getAuthority();
        }

**Comment by echisan** [comment]
那个isRemember是用于确定生成token的有效期的 跟角色没啥关系的
后面的没看懂0.0
