### ISSUE TITLE
老哥请问token过期时间一小时，我在这一小时内访问是不是应该像session一样刷新它?

### ISSUE THREAD

**Issue by LiuQiV5** [echisan/springboot-jwt-demo#6]
我的想法是在创建token的时候在载荷中加入一个createdate字段，每次校验的时候刷新一下这个字段生成一个新token，这样的话每次前台请求的时候就都要带一个新的token了，但是这样做我觉得怪怪的很不友好，请问老哥你有什么想法吗？

**Comment by echisan** [comment]
没有必要呢，因为负荷里有一个过期的时间了，每次鉴权的时候判断一下是否过期了，如果过期了再让客户端重新走一遍授权的流程就行了
