### ISSUE TITLE
要是做动态权限管理怎么弄

### ISSUE THREAD

**Issue by 670141733** [echisan/springboot-jwt-demo#8]
SpringSecurity+jwt 怎么实现动态权限管理

**Comment by echisan** [comment]
这个更多的是springsecurity的范畴,具体去搜一下springsecurity如何从数据库里加载权限信息，然后再把对应的信息在用户登陆的时候从数据库里读取并且存储到token里

**Comment by 670141733** [comment]
好的，谢谢
