### ISSUE TITLE
JwtAuthenticationFilter NullPointException

### ISSUE THREAD

**Issue by vgbhfive** [echisan/springboot-jwt-demo#9]
rememberMe class is Null.

`2019-04-03 16:31:57.229 ERROR 17900 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

java.lang.NullPointerException: null
	at cn.vgbhfive.graduationproject.filter.JwtAuthenticationFilter.successfulAuthentication(JwtAuthenticationFilter.java:64) ~[classes/:na]
`
第64行代码：
`boolean isRemember = rememberMe.get() == 1;`
所以，rememberMe为空。

![1](https://user-images.githubusercontent.com/21358392/55464974-c8de3180-562e-11e9-8694-e457a1244f89.jpg)

**Comment by echisan** [comment]
https://github.com/echisan/springboot-jwt-demo/blob/master/src/main/java/cn/echisan/springbootjwtdemo/filter/JWTAuthenticationFilter.java#L42 这一步有做吗

**Comment by vgbhfive** [comment]
不细心，没看见，解决问题了
